---
env:
  global:
  - secure: |-
      YrnNakmop/HyiZHEkvEbm9qkig4ZoorenlRRbm7CeITMflrpXKgOEuP/VK/K
      5FW85Qmut/JsYnwlbBsFliI4qEhcqP8Df2uBd8dAt2ZrIMJb7bY3L1jlL+Ek
      ogBlfvqMzPJwo44OPsb83RtcevCXd+E7sAroJz/emNGagr3Jic4=
language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - ruby-head
  - 2.0.0
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rspec spec
after_success:
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - git remote add heroku git@heroku.com:search-properties.git
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  - heroku keys:clear
  - yes | heroku keys:add
  - yes | git push heroku master
