---
env:
  global:
  - secure: |-
      YrnNakmop/HyiZHEkvEbm9qkig4ZoorenlRRbm7CeITMflrpXKgOEuP/VK/K
      5FW85Qmut/JsYnwlbBsFliI4qEhcqP8Df2uBd8dAt2ZrIMJb7bY3L1jlL+Ek
      ogBlfvqMzPJwo44OPsb83RtcevCXd+E7sAroJz/emNGagr3Jic4=
language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - ruby-head
  - 2.0.0
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rspec spec
after_success:
  - gem install heroku
  - yes | ruby travis_deployer.rb
  - heroku keys:clear
  - yes | heroku keys:add
  - git push heroku master
